server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 960216
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 10
      max-wait: 60
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      validation-query-timeout: 100
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      async-close-connection-enable: true
      aop-patterns: org.holy.tkmapper.service.*
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    # property-naming-strategy: SNAKE_CASE


mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql


mapper:
  identity: MYSQL


# logging
logging:
  file: /var/log/docs/log.log
  group:
    service: org.holy.tkmapper
  level:
    root: info
    web: debug
    sql: debug
    service: debug